//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaymentGateway.Datalayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class MerchantKey
    {
        public int KeyId { get; set; }
        public int merId { get; set; }
        public string PublicKey { get; set; }
        public string PrivateKey { get; set; }
    }
}
