//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaymentGateway.Datalayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PaymentGatewayEntities : DbContext
    {
        public PaymentGatewayEntities()
            : base("name=PaymentGatewayEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Merchant> Merchants { get; set; }
        public virtual DbSet<MerchantKey> MerchantKeys { get; set; }
        public virtual DbSet<ApplicationLog> ApplicationLogs { get; set; }
        public virtual DbSet<Token> Tokens { get; set; }
        public virtual DbSet<MerchantDetail> MerchantDetails { get; set; }
        public virtual DbSet<TransactionLog> TransactionLogs { get; set; }
    }
}
