//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaymentGateway.Datalayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Token
    {
        public int TokenId { get; set; }
        public string MerchantId { get; set; }
        public string ClientToken { get; set; }
        public System.DateTime DateCreated { get; set; }
    }
}
