//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaymentGateway.Datalayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionLog
    {
        public int TransactionId { get; set; }
        public string TransactionIdentifiyer { get; set; }
        public string MerchantId { get; set; }
        public Nullable<bool> IsSuccess { get; set; }
        public Nullable<decimal> AmountCredited { get; set; }
        public string BankResponse { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public int CVC { get; set; }
        public string CardNumber { get; set; }
        public int ExpiryMonth { get; set; }
        public int ExpiryYear { get; set; }
    }
}
